# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HY_Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniq', models.PositiveIntegerField(blank=True, null=True, verbose_name='Unique ID')),
                ('bl_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='Building ID')),
                ('addr', models.CharField(max_length=200, verbose_name='Address')),
                ('gps_x', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Latitude')),
                ('gps_y', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Longtitude')),
                ('oc_day', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Occupancy: Day')),
                ('oc_night', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Occupancy: Night')),
                ('no_floor', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='No. of Floors')),
                ('bas_prsnt', models.BooleanField(verbose_name='Basement')),
                ('yr_constr', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Year of Construction')),
                ('yr_extn', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Year of Extension(If Any)')),
                ('acc_level', models.CharField(max_length=10, verbose_name='Access Level')),
                ('bl_use', models.CharField(max_length=50, verbose_name='Building Use')),
                ('s_zone', models.PositiveIntegerField(verbose_name='Seismic Zone')),
            ],
            options={
                'verbose_name': 'Hybrid Building',
                'verbose_name_plural': 'Hybrid Buildings',
            },
        ),
        migrations.CreateModel(
            name='MS_Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniq', models.PositiveIntegerField(blank=True, null=True, verbose_name='Unique ID')),
                ('bl_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='Building ID')),
                ('addr', models.CharField(max_length=200, verbose_name='Address')),
                ('gps_x', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Latitude')),
                ('gps_y', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Longtitude')),
                ('oc_day', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Occupancy: Day')),
                ('oc_night', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Occupancy: Night')),
                ('no_floor', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='No. of Floors')),
                ('bas_prsnt', models.BooleanField(verbose_name='Basement')),
                ('yr_constr', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Year of Construction')),
                ('yr_extn', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Year of Extension(If Any)')),
                ('acc_level', models.CharField(max_length=10, verbose_name='Access Level')),
                ('bl_use', models.CharField(max_length=50, verbose_name='Building Use')),
                ('s_zone', models.PositiveIntegerField(verbose_name='Seismic Zone')),
            ],
            options={
                'verbose_name': 'Masonary Building',
                'verbose_name_plural': 'Masonary Buildings',
            },
        ),
        migrations.CreateModel(
            name='RC_Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniq', models.PositiveIntegerField(blank=True, null=True, verbose_name='Unique ID')),
                ('bl_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='Building ID')),
                ('addr', models.CharField(max_length=200, verbose_name='Address')),
                ('gps_x', models.DecimalField(decimal_places=7, max_digits=9, verbose_name='Latitude')),
                ('gps_y', models.DecimalField(decimal_places=7, max_digits=9, verbose_name='Longtitude')),
                ('oc_day', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Day')),
                ('oc_night', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Night')),
                ('no_floor', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='No. of Floors')),
                ('bas_prsnt', models.CharField(choices=[('P', 'Presesnt'), ('A', 'Absent')], max_length=1, verbose_name='Basement')),
                ('yr_constr', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Year of Construction')),
                ('yr_extn', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Year of Extension (If Any)')),
                ('bl_use', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Mixed', 'Mixed'), ('Others', 'Others')], max_length=50, verbose_name='Building Use')),
                ('op_bl_use', models.CharField(blank=True, max_length=50, null=True, verbose_name='If Others, Specify')),
                ('acc_level', models.CharField(choices=[('FULL', 'FULL'), ('PARTIAL', 'PARTIAL'), ('NO', 'NO')], max_length=10, verbose_name='Access Level')),
                ('s_zone', models.PositiveIntegerField(choices=[(1, 'II and III'), (2, 'IV'), (3, 'V')], verbose_name='Seismic Zone')),
                ('dt_tkn', models.DateTimeField(blank=True, verbose_name='Taken On')),
                ('vrt_irr', models.PositiveIntegerField(choices=[(0, 'Absent'), (1, 'Present')], verbose_name='Vertical Irregularities')),
                ('pl_irr', models.PositiveIntegerField(choices=[(0, 'Absent'), (1, 'Present')], verbose_name='Plan Irregularities')),
                ('hvy_ovh', models.PositiveIntegerField(choices=[(0, 'Absent'), (1, 'Present')], verbose_name='Heavy Overhangs')),
                ('shr_col', models.PositiveIntegerField(choices=[(0, 'Absent'), (1, 'Present')], verbose_name='Short Column')),
                ('frm_act', models.NullBooleanField(verbose_name='Frame Action Present')),
                ('soft_st', models.PositiveIntegerField(blank=True, choices=[(0, 'Absent'), (1, 'Present')], default=0, verbose_name='Soft Storey')),
                ('op_prk', models.PositiveIntegerField(choices=[(0, 'Absent'), (1, 'Present')], verbose_name='Open Parking at Ground Level')),
                ('ab_prt', models.PositiveIntegerField(choices=[(0, 'Absent'), (1, 'Present')], verbose_name='Absence of Partition Walls in Ground or Any Intermediate')),
                ('st_shp', models.PositiveIntegerField(choices=[(0, 'Absent'), (1, 'Present')], verbose_name='Storey for Shops or Other Commercial Use')),
                ('tl_htg', models.PositiveIntegerField(choices=[(0, 'Absent'), (1, 'Present')], verbose_name='Taller Height in Ground or Any Other Intermediate Storey')),
                ('rf_sign', models.NullBooleanField(default=False, verbose_name='Marquees/Hoardings/Roof Signs')),
                ('ac_grl', models.NullBooleanField(default=False, verbose_name='AC Units/Grillwork')),
                ('el_prp', models.NullBooleanField(default=False, verbose_name='Elaborate Parapets')),
                ('hv_elf', models.NullBooleanField(default=False, verbose_name='Heavy Elevation Features')),
                ('hv_cnp', models.NullBooleanField(default=False, verbose_name='Heavy Canopies')),
                ('sb_bal', models.NullBooleanField(default=False, verbose_name='Substantial Balconies')),
                ('hv_cld', models.NullBooleanField(default=False, verbose_name='Heavy Cladding')),
                ('str_gl', models.NullBooleanField(default=False, verbose_name='Structural Glazing')),
                ('sign_url', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'RC Building',
                'verbose_name_plural': 'RC Buildings',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2, unique=True)),
                ('mem_1', models.CharField(max_length=50, verbose_name='Member 1')),
                ('mem_2', models.CharField(blank=True, max_length=50, verbose_name='Member 2')),
                ('mem_3', models.CharField(blank=True, max_length=50, verbose_name='Member 3')),
                ('mem_4', models.CharField(blank=True, max_length=50, verbose_name='Member 4')),
            ],
        ),
        migrations.AddField(
            model_name='rc_building',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='survey.Team'),
        ),
        migrations.AddField(
            model_name='ms_building',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='survey.Team'),
        ),
        migrations.AddField(
            model_name='hy_building',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='survey.Team'),
        ),
    ]
