# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ms_building',
            name='diap_ac',
        ),
        migrations.AddField(
            model_name='ms_building',
            name='diap_ab',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No')], default=1, verbose_name='Diaphragm Action Absent?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ms_building',
            name='prt_opn',
            field=models.PositiveIntegerField(choices=[(0, 'Small (<1/3)'), (1, 'Moderate (1/3 to 2/3)'), (2, 'Large (>2/3)')], verbose_name='Percentage of Openings'),
        ),
    ]
