# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='s_zone',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='building',
            name='yr_constr',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='building',
            name='yr_extn',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
