# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rc_building',
            name='dt_tkn',
            field=models.DateTimeField(blank=True, verbose_name='Taken On'),
        ),
    ]
