# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hy_building',
            name='gps_str',
            field=models.CharField(default='Dropped pin near Sector 6, Gandhinagar, Gujarat 382006  https://goo.gl/maps/FfkdJc3N7mq', max_length=200, verbose_name='Enter Copied Location String'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ms_building',
            name='gps_str',
            field=models.CharField(default='Dropped pin near Sector 6, Gandhinagar, Gujarat 382006  https://goo.gl/maps/FfkdJc3N7mq', max_length=200, verbose_name='Enter Copied Location String'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rc_building',
            name='gps_str',
            field=models.CharField(default='Dropped pin near Sector 6, Gandhinagar, Gujarat 382006  https://goo.gl/maps/FfkdJc3N7mq', max_length=200, verbose_name='Enter Copied Location String'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hy_building',
            name='gps_x',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='hy_building',
            name='gps_y',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, verbose_name='Longtitude'),
        ),
        migrations.AlterField(
            model_name='ms_building',
            name='gps_x',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='ms_building',
            name='gps_y',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, verbose_name='Longtitude'),
        ),
        migrations.AlterField(
            model_name='rc_building',
            name='gps_x',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='rc_building',
            name='gps_y',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, verbose_name='Longtitude'),
        ),
    ]
