# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rc_building',
            name='bl_slp',
            field=models.PositiveIntegerField(choices=[(0, 'Absent'), (1, 'Present')], default=0, verbose_name='Building on Sloppy Ground'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rc_building',
            name='pr_stb',
            field=models.PositiveIntegerField(choices=[(0, 'Absent'), (1, 'Present')], default=0, verbose_name='Presence of Setback'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rc_building',
            name='vrt_irr',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Absent'), (1, 'Present')], default=0, verbose_name='Vertical Irregularities'),
        ),
    ]
