# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20170613_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rc',
            name='op_park_grnd',
        ),
    ]
