# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20170624_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hy_building',
            name='gps_str',
            field=models.CharField(blank=True, max_length=200, verbose_name='Enter Copied Location String'),
        ),
        migrations.AlterField(
            model_name='ms_building',
            name='gps_str',
            field=models.CharField(blank=True, max_length=200, verbose_name='Enter Copied Location String'),
        ),
        migrations.AlterField(
            model_name='rc_building',
            name='gps_str',
            field=models.CharField(blank=True, max_length=200, verbose_name='Enter Copied Location String'),
        ),
    ]
