# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20170620_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='rc_building',
            name='ir_plc',
            field=models.PositiveIntegerField(choices=[(0, 'Absent'), (1, 'Present')], default=0, verbose_name='Irregular Plan Configuration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rc_building',
            name='re_crn',
            field=models.PositiveIntegerField(choices=[(0, 'Absent'), (1, 'Present')], default=0, verbose_name='Re-Entrant Corners'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rc_building',
            name='pl_irr',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Absent'), (1, 'Present')], default=0, verbose_name='Plan Irregularities'),
        ),
    ]
