# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20170624_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ms_building',
            name='un_flr',
        ),
        migrations.AddField(
            model_name='ms_building',
            name='cnt_bld',
            field=models.PositiveIntegerField(choices=[(0, 'Absent'), (1, 'Present')], default=1, verbose_name='Contiguous Building'),
            preserve_default=False,
        ),
    ]
