# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_remove_rc_op_park_grnd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.RemoveField(
            model_name='rc',
            name='abs_prt_walls',
        ),
        migrations.RemoveField(
            model_name='rc',
            name='st_for_comm',
        ),
        migrations.RemoveField(
            model_name='rc',
            name='tl_ht_grnd',
        ),
        migrations.RemoveField(
            model_name='rc',
            name='vrt_irrg',
        ),
        migrations.AddField(
            model_name='rc',
            name='hvy_ovh',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rc',
            name='pl_irr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rc',
            name='shr_col',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rc',
            name='vrt_irr',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='building',
            name='acc_level',
            field=models.CharField(max_length=10, verbose_name='Access Level'),
        ),
        migrations.AlterField(
            model_name='building',
            name='addr',
            field=models.CharField(max_length=200, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='building',
            name='bl_id',
            field=models.PositiveIntegerField(verbose_name='Building ID'),
        ),
        migrations.AlterField(
            model_name='building',
            name='bl_use',
            field=models.CharField(max_length=50, verbose_name='Building Use'),
        ),
        migrations.AlterField(
            model_name='building',
            name='gps_x',
            field=models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='building',
            name='gps_y',
            field=models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Longtitude'),
        ),
        migrations.AlterField(
            model_name='building',
            name='no_floor',
            field=models.PositiveSmallIntegerField(verbose_name='No. of Floors'),
        ),
        migrations.AlterField(
            model_name='building',
            name='oc_day',
            field=models.PositiveIntegerField(verbose_name='Occupancy: Day'),
        ),
        migrations.AlterField(
            model_name='building',
            name='oc_night',
            field=models.PositiveIntegerField(verbose_name='Occupancy: Night'),
        ),
        migrations.AlterField(
            model_name='building',
            name='s_zone',
            field=models.PositiveIntegerField(verbose_name='Seismic Zone'),
        ),
        migrations.AlterField(
            model_name='building',
            name='yr_constr',
            field=models.PositiveSmallIntegerField(verbose_name='Year of Construction'),
        ),
        migrations.AlterField(
            model_name='building',
            name='yr_extn',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Year of Extension(If Any)'),
        ),
    ]
