# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20170620_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='rc_building',
            name='md_hrp',
            field=models.PositiveIntegerField(choices=[(0, 'Absent'), (1, 'Present')], default=0, verbose_name='Moderate Horizontal Projections'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rc_building',
            name='sb_hrp',
            field=models.PositiveIntegerField(choices=[(0, 'Absent'), (1, 'Present')], default=0, verbose_name='Substantial Horizontal Projections'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rc_building',
            name='hvy_ovh',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Absent'), (1, 'Present')], default=0, verbose_name='Heavy Overhangs'),
        ),
    ]
