# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20170620_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='rc_building',
            name='ap_qlt',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Good'), (1, 'Moderate'), (2, 'Poor')], default=0, verbose_name='Apparent Quality'),
        ),
        migrations.AddField(
            model_name='rc_building',
            name='maintc',
            field=models.PositiveIntegerField(choices=[(0, 'Good'), (1, 'Moderate'), (2, 'Poor')], default=0, verbose_name='Maintainence'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rc_building',
            name='ql_mat',
            field=models.PositiveIntegerField(choices=[(0, 'Good'), (1, 'Moderate'), (2, 'Poor')], default=0, verbose_name='Apparent Quality of Construction and Materials'),
            preserve_default=False,
        ),
    ]
