# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20170614_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='HY_Building',
            fields=[
                ('uniq', models.PositiveIntegerField(unique=True, verbose_name='Unique ID')),
                ('bl_id', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Building ID')),
                ('addr', models.CharField(max_length=200, verbose_name='Address')),
                ('gps_x', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Latitude')),
                ('gps_y', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Longtitude')),
                ('oc_day', models.PositiveIntegerField(verbose_name='Occupancy: Day')),
                ('oc_night', models.PositiveIntegerField(verbose_name='Occupancy: Night')),
                ('no_floor', models.PositiveSmallIntegerField(verbose_name='No. of Floors')),
                ('yr_constr', models.PositiveSmallIntegerField(verbose_name='Year of Construction')),
                ('yr_extn', models.PositiveSmallIntegerField(blank=True, verbose_name='Year of Extension(If Any)')),
                ('acc_level', models.CharField(max_length=10, verbose_name='Access Level')),
                ('bl_use', models.CharField(max_length=50, verbose_name='Building Use')),
                ('s_zone', models.PositiveIntegerField(verbose_name='Seismic Zone')),
            ],
        ),
        migrations.CreateModel(
            name='MS_Building',
            fields=[
                ('uniq', models.PositiveIntegerField(unique=True, verbose_name='Unique ID')),
                ('bl_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Building ID')),
                ('addr', models.CharField(max_length=200, verbose_name='Address')),
                ('gps_x', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Latitude')),
                ('gps_y', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Longtitude')),
                ('oc_day', models.PositiveIntegerField(verbose_name='Occupancy: Day')),
                ('oc_night', models.PositiveIntegerField(verbose_name='Occupancy: Night')),
                ('no_floor', models.PositiveSmallIntegerField(verbose_name='No. of Floors')),
                ('yr_constr', models.PositiveSmallIntegerField(verbose_name='Year of Construction')),
                ('yr_extn', models.PositiveSmallIntegerField(blank=True, verbose_name='Year of Extension(If Any)')),
                ('acc_level', models.CharField(max_length=10, verbose_name='Access Level')),
                ('bl_use', models.CharField(max_length=50, verbose_name='Building Use')),
                ('s_zone', models.PositiveIntegerField(verbose_name='Seismic Zone')),
            ],
        ),
        migrations.CreateModel(
            name='RC_Building',
            fields=[
                ('uniq', models.PositiveIntegerField(unique=True, verbose_name='Unique ID')),
                ('bl_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Building ID')),
                ('addr', models.CharField(max_length=200, verbose_name='Address')),
                ('gps_x', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Latitude')),
                ('gps_y', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Longtitude')),
                ('oc_day', models.PositiveIntegerField(verbose_name='Occupancy: Day')),
                ('oc_night', models.PositiveIntegerField(verbose_name='Occupancy: Night')),
                ('no_floor', models.PositiveSmallIntegerField(verbose_name='No. of Floors')),
                ('yr_constr', models.PositiveSmallIntegerField(verbose_name='Year of Construction')),
                ('yr_extn', models.PositiveSmallIntegerField(blank=True, verbose_name='Year of Extension(If Any)')),
                ('acc_level', models.CharField(max_length=10, verbose_name='Access Level')),
                ('bl_use', models.CharField(max_length=50, verbose_name='Building Use')),
                ('s_zone', models.PositiveIntegerField(verbose_name='Seismic Zone')),
                ('soft_st', models.BooleanField(default=False, verbose_name='Soft Storey')),
                ('vrt_irr', models.BooleanField(default=False, verbose_name='Vertical Irregularities')),
                ('pl_irr', models.BooleanField(default=False)),
                ('hvy_ovh', models.BooleanField(default=False)),
                ('shr_col', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='building',
            name='team',
        ),
        migrations.DeleteModel(
            name='RC',
        ),
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default='A', max_length=2, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='mem_1',
            field=models.CharField(max_length=50, verbose_name='Member 1'),
        ),
        migrations.AlterField(
            model_name='team',
            name='mem_2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Member 2'),
        ),
        migrations.AlterField(
            model_name='team',
            name='mem_3',
            field=models.CharField(blank=True, max_length=50, verbose_name='Member 3'),
        ),
        migrations.AlterField(
            model_name='team',
            name='mem_4',
            field=models.CharField(blank=True, max_length=50, verbose_name='Member 4'),
        ),
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.AddField(
            model_name='rc_building',
            name='team',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='survey.Team'),
        ),
        migrations.AddField(
            model_name='ms_building',
            name='team',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='survey.Team'),
        ),
        migrations.AddField(
            model_name='hy_building',
            name='team',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='survey.Team'),
        ),
    ]
