# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20170620_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='rc_building',
            name='pnding',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Absent'), (1, 'Present')], default=0, verbose_name='Pounding'),
        ),
        migrations.AddField(
            model_name='rc_building',
            name='pr_qlt',
            field=models.PositiveIntegerField(choices=[(0, 'Absent'), (1, 'Present')], default=0, verbose_name='Poor Apparent Quality of Adjacent Buildings'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rc_building',
            name='un_flr',
            field=models.PositiveIntegerField(choices=[(0, 'Absent'), (1, 'Present')], default=0, verbose_name='Unaligned Floors'),
            preserve_default=False,
        ),
    ]
