# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20170620_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='rc_building',
            name='soil_cn',
            field=models.IntegerField(choices=[(0, 'Medium'), (1, 'Hard'), (-1, 'Soft')], default=0, verbose_name='Soil Condtition'),
            preserve_default=False,
        ),
    ]
