# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20170614_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rc_building',
            name='oc_day',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Occupancy: Day'),
        ),
        migrations.AlterField(
            model_name='rc_building',
            name='oc_night',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Occupancy: Night'),
        ),
    ]
