# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20170614_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='rc_building',
            name='bas_prsnt',
            field=models.BooleanField(default=False, verbose_name='Basement'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rc_building',
            name='no_floor',
            field=models.DecimalField(decimal_places=0, max_digits=2, verbose_name='No. of Floors'),
        ),
        migrations.AlterField(
            model_name='rc_building',
            name='yr_constr',
            field=models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Year of Construction'),
        ),
        migrations.AlterField(
            model_name='rc_building',
            name='yr_extn',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Year of Extension(If Any)'),
        ),
    ]
