# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20170620_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rc_building',
            name='frm_act',
            field=models.PositiveIntegerField(choices=[(0, 'Absent'), (1, 'Present')], verbose_name='Frame Action'),
        ),
    ]
