# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20170615_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='rc_building',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rc_building',
            name='bl_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Building ID'),
        ),
    ]
