# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20170615_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='hy_building',
            name='bas_prsnt',
            field=models.BooleanField(default=False, verbose_name='Basement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hy_building',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ms_building',
            name='bas_prsnt',
            field=models.BooleanField(default=False, verbose_name='Basement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ms_building',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hy_building',
            name='bl_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Building ID'),
        ),
        migrations.AlterField(
            model_name='hy_building',
            name='no_floor',
            field=models.DecimalField(decimal_places=0, max_digits=2, verbose_name='No. of Floors'),
        ),
        migrations.AlterField(
            model_name='hy_building',
            name='oc_day',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Occupancy: Day'),
        ),
        migrations.AlterField(
            model_name='hy_building',
            name='oc_night',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Occupancy: Night'),
        ),
        migrations.AlterField(
            model_name='hy_building',
            name='uniq',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='hy_building',
            name='yr_constr',
            field=models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Year of Construction'),
        ),
        migrations.AlterField(
            model_name='hy_building',
            name='yr_extn',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Year of Extension(If Any)'),
        ),
        migrations.AlterField(
            model_name='ms_building',
            name='bl_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Building ID'),
        ),
        migrations.AlterField(
            model_name='ms_building',
            name='no_floor',
            field=models.DecimalField(decimal_places=0, max_digits=2, verbose_name='No. of Floors'),
        ),
        migrations.AlterField(
            model_name='ms_building',
            name='oc_day',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Occupancy: Day'),
        ),
        migrations.AlterField(
            model_name='ms_building',
            name='oc_night',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Occupancy: Night'),
        ),
        migrations.AlterField(
            model_name='ms_building',
            name='uniq',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='ms_building',
            name='yr_constr',
            field=models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Year of Construction'),
        ),
        migrations.AlterField(
            model_name='ms_building',
            name='yr_extn',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Year of Extension(If Any)'),
        ),
        migrations.AlterField(
            model_name='rc_building',
            name='hvy_ovh',
            field=models.BooleanField(default=False, verbose_name='Heavy Overhangs'),
        ),
        migrations.AlterField(
            model_name='rc_building',
            name='pl_irr',
            field=models.BooleanField(default=False, verbose_name='Plan Irregularities'),
        ),
        migrations.AlterField(
            model_name='rc_building',
            name='shr_col',
            field=models.BooleanField(default=False, verbose_name='Short Column'),
        ),
    ]
