# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 09:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20170621_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rc_building',
            name='no_floor',
            field=models.DecimalField(decimal_places=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0)], verbose_name='No. of Floors'),
        ),
        migrations.AlterField(
            model_name='rc_building',
            name='oc_day',
            field=models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='rc_building',
            name='oc_night',
            field=models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Night'),
        ),
        migrations.AlterField(
            model_name='rc_building',
            name='yr_constr',
            field=models.DecimalField(decimal_places=0, max_digits=4, validators=[django.core.validators.MinValueValidator(1800)], verbose_name='Year of Construction'),
        ),
        migrations.AlterField(
            model_name='rc_building',
            name='yr_extn',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(1900)], verbose_name='Year of Extension (If Any)'),
        ),
    ]
