# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 11:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20170621_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rc_building',
            name='sign_url',
            field=models.CharField(max_length=300, validators=[django.core.validators.URLValidator]),
        ),
        migrations.AlterField(
            model_name='rc_building',
            name='yr_constr',
            field=models.DecimalField(decimal_places=0, max_digits=4, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2017)], verbose_name='Year of Construction'),
        ),
        migrations.AlterField(
            model_name='rc_building',
            name='yr_extn',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2017)], verbose_name='Year of Extension (If Any)'),
        ),
    ]
