# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_auto_20170621_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rc_building',
            name='frm_act',
            field=models.PositiveIntegerField(choices=[(-1, 'Absent'), (1, 'Present'), (0, 'Not Sure')], verbose_name='Frame Action'),
        ),
    ]
