# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_cm_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cm_building',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='survey.Team'),
        ),
        migrations.AlterField(
            model_name='hy_building',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='survey.Team'),
        ),
        migrations.AlterField(
            model_name='ms_building',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='survey.Team'),
        ),
        migrations.AlterField(
            model_name='rc_building',
            name='soft_st',
            field=models.NullBooleanField(verbose_name='Soft Storey'),
        ),
        migrations.AlterField(
            model_name='rc_building',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='survey.Team'),
        ),
    ]
