# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_auto_20170615_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cm_building',
            name='team',
        ),
        migrations.DeleteModel(
            name='CM_Building',
        ),
    ]
