# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_auto_20170621_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rc_building',
            name='pl_irr',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'None'), (1, 'Moderate'), (2, 'Extreme')], default=0, verbose_name='Plan Irregularities'),
        ),
    ]
