# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_auto_20170621_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='rc_building',
            name='perf_score',
            field=models.IntegerField(default=1, verbose_name='Performance Score'),
            preserve_default=False,
        ),
    ]
