# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_rc_building_perf_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rc_building',
            name='ap_qlt',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Good'), (1, 'Moderate'), (2, 'Poor')], verbose_name='Apparent Quality'),
        ),
        migrations.AlterField(
            model_name='rc_building',
            name='hvy_ovh',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Absent'), (1, 'Present')], verbose_name='Heavy Overhangs'),
        ),
        migrations.AlterField(
            model_name='rc_building',
            name='pl_irr',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'None'), (1, 'Moderate'), (2, 'Extreme')], verbose_name='Plan Irregularities'),
        ),
        migrations.AlterField(
            model_name='rc_building',
            name='pnding',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Absent'), (1, 'Present')], verbose_name='Pounding'),
        ),
        migrations.AlterField(
            model_name='rc_building',
            name='soft_st',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Absent'), (1, 'Present')], verbose_name='Soft Storey'),
        ),
        migrations.AlterField(
            model_name='rc_building',
            name='vrt_irr',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Absent'), (1, 'Present')], verbose_name='Vertical Irregularities'),
        ),
    ]
