# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_auto_20170615_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='rc_building',
            name='ac_grl',
            field=models.NullBooleanField(default=False, verbose_name='AC Units/Grillwork'),
        ),
        migrations.AddField(
            model_name='rc_building',
            name='el_prp',
            field=models.NullBooleanField(default=False, verbose_name='Elaborate Parapets'),
        ),
        migrations.AddField(
            model_name='rc_building',
            name='hv_cld',
            field=models.NullBooleanField(default=False, verbose_name='Heavy Cladding'),
        ),
        migrations.AddField(
            model_name='rc_building',
            name='hv_cnp',
            field=models.NullBooleanField(default=False, verbose_name='Heavy Canopies'),
        ),
        migrations.AddField(
            model_name='rc_building',
            name='hv_elf',
            field=models.NullBooleanField(default=False, verbose_name='Heavy Elevation Features'),
        ),
        migrations.AddField(
            model_name='rc_building',
            name='rf_sign',
            field=models.NullBooleanField(default=False, verbose_name='Marquees/Hoardings/Roof Signs'),
        ),
        migrations.AddField(
            model_name='rc_building',
            name='sb_bal',
            field=models.NullBooleanField(default=False, verbose_name='Substantial Balconies'),
        ),
        migrations.AddField(
            model_name='rc_building',
            name='str_gl',
            field=models.NullBooleanField(default=False, verbose_name='Structural Glazing'),
        ),
        migrations.AlterField(
            model_name='rc_building',
            name='bas_prsnt',
            field=models.NullBooleanField(default=False, verbose_name='Basement'),
        ),
        migrations.AlterField(
            model_name='rc_building',
            name='hvy_ovh',
            field=models.NullBooleanField(verbose_name='Heavy Overhangs'),
        ),
        migrations.AlterField(
            model_name='rc_building',
            name='pl_irr',
            field=models.NullBooleanField(verbose_name='Plan Irregularities'),
        ),
        migrations.AlterField(
            model_name='rc_building',
            name='shr_col',
            field=models.NullBooleanField(verbose_name='Short Column'),
        ),
        migrations.AlterField(
            model_name='rc_building',
            name='vrt_irr',
            field=models.NullBooleanField(verbose_name='Vertical Irregularities'),
        ),
    ]
