# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_auto_20170622_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rc_building',
            name='perf_score',
            field=models.IntegerField(blank=True, verbose_name='Performance Score'),
        ),
    ]
