# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 22:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_auto_20170617_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='rc_building',
            name='dt_tkn',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 16, 22, 36, 41, 630500, tzinfo=utc), verbose_name='Taken On'),
            preserve_default=False,
        ),
    ]
