# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_auto_20170622_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rc_building',
            name='bas_prsnt',
            field=models.PositiveIntegerField(choices=[(0, 'Absent'), (1, 'Present')], verbose_name='Basement'),
        ),
    ]
