# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_rc_building_dt_tkn'),
    ]

    operations = [
        migrations.AddField(
            model_name='rc_building',
            name='sign_url',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rc_building',
            name='acc_level',
            field=models.CharField(choices=[('FULL', 'FULL'), ('PARTIAL', 'PARTIAL'), ('NO', 'NO')], max_length=10, verbose_name='Access Level'),
        ),
    ]
