# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 08:31
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_auto_20170622_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='hy_building',
            name='dt_tkn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 6, 22, 8, 30, 23, 619461, tzinfo=utc), verbose_name='Taken On'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hy_building',
            name='op_bl_use',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='If Others, Specify'),
        ),
        migrations.AddField(
            model_name='hy_building',
            name='perf_score',
            field=models.IntegerField(blank=True, default=1, verbose_name='Performance Score'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hy_building',
            name='sign_url',
            field=models.CharField(default='ytyuio', max_length=300, validators=[django.core.validators.URLValidator]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hy_building',
            name='soil_cn',
            field=models.IntegerField(choices=[(0, 'Medium'), (1, 'Hard'), (-1, 'Soft')], default=1, verbose_name='Soil Condtition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ms_building',
            name='dt_tkn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 6, 22, 8, 30, 50, 31559, tzinfo=utc), verbose_name='Taken On'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ms_building',
            name='op_bl_use',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='If Others, Specify'),
        ),
        migrations.AddField(
            model_name='ms_building',
            name='perf_score',
            field=models.IntegerField(blank=True, default=1, verbose_name='Performance Score'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ms_building',
            name='sign_url',
            field=models.CharField(default='sdfsd', max_length=300, validators=[django.core.validators.URLValidator]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ms_building',
            name='soil_cn',
            field=models.IntegerField(choices=[(0, 'Medium'), (1, 'Hard'), (-1, 'Soft')], default=1, verbose_name='Soil Condtition'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hy_building',
            name='acc_level',
            field=models.CharField(choices=[('FULL', 'FULL'), ('PARTIAL', 'PARTIAL'), ('NO', 'NO')], max_length=10, verbose_name='Access Level'),
        ),
        migrations.AlterField(
            model_name='hy_building',
            name='bas_prsnt',
            field=models.PositiveIntegerField(choices=[(0, 'Absent'), (1, 'Present')], verbose_name='Basement'),
        ),
        migrations.AlterField(
            model_name='hy_building',
            name='bl_use',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Mixed', 'Mixed'), ('Others', 'Others')], max_length=50, verbose_name='Building Use'),
        ),
        migrations.AlterField(
            model_name='hy_building',
            name='gps_x',
            field=models.DecimalField(decimal_places=7, max_digits=9, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='hy_building',
            name='gps_y',
            field=models.DecimalField(decimal_places=7, max_digits=9, verbose_name='Longtitude'),
        ),
        migrations.AlterField(
            model_name='hy_building',
            name='no_floor',
            field=models.DecimalField(decimal_places=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0)], verbose_name='No. of Floors'),
        ),
        migrations.AlterField(
            model_name='hy_building',
            name='oc_day',
            field=models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='hy_building',
            name='oc_night',
            field=models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Night'),
        ),
        migrations.AlterField(
            model_name='hy_building',
            name='s_zone',
            field=models.PositiveIntegerField(choices=[(1, 'II and III'), (2, 'IV'), (3, 'V')], verbose_name='Seismic Zone'),
        ),
        migrations.AlterField(
            model_name='hy_building',
            name='yr_constr',
            field=models.DecimalField(decimal_places=0, max_digits=4, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2017)], verbose_name='Year of Construction'),
        ),
        migrations.AlterField(
            model_name='hy_building',
            name='yr_extn',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2017)], verbose_name='Year of Extension (If Any)'),
        ),
        migrations.AlterField(
            model_name='ms_building',
            name='acc_level',
            field=models.CharField(choices=[('FULL', 'FULL'), ('PARTIAL', 'PARTIAL'), ('NO', 'NO')], max_length=10, verbose_name='Access Level'),
        ),
        migrations.AlterField(
            model_name='ms_building',
            name='bas_prsnt',
            field=models.PositiveIntegerField(choices=[(0, 'Absent'), (1, 'Present')], verbose_name='Basement'),
        ),
        migrations.AlterField(
            model_name='ms_building',
            name='bl_use',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Mixed', 'Mixed'), ('Others', 'Others')], max_length=50, verbose_name='Building Use'),
        ),
        migrations.AlterField(
            model_name='ms_building',
            name='gps_x',
            field=models.DecimalField(decimal_places=7, max_digits=9, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='ms_building',
            name='gps_y',
            field=models.DecimalField(decimal_places=7, max_digits=9, verbose_name='Longtitude'),
        ),
        migrations.AlterField(
            model_name='ms_building',
            name='no_floor',
            field=models.DecimalField(decimal_places=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0)], verbose_name='No. of Floors'),
        ),
        migrations.AlterField(
            model_name='ms_building',
            name='oc_day',
            field=models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='ms_building',
            name='oc_night',
            field=models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Night'),
        ),
        migrations.AlterField(
            model_name='ms_building',
            name='s_zone',
            field=models.PositiveIntegerField(choices=[(1, 'II and III'), (2, 'IV'), (3, 'V')], verbose_name='Seismic Zone'),
        ),
        migrations.AlterField(
            model_name='ms_building',
            name='yr_constr',
            field=models.DecimalField(decimal_places=0, max_digits=4, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2017)], verbose_name='Year of Construction'),
        ),
        migrations.AlterField(
            model_name='ms_building',
            name='yr_extn',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2017)], verbose_name='Year of Extension (If Any)'),
        ),
    ]
