# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_auto_20170617_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rc_building',
            name='s_zone',
            field=models.PositiveIntegerField(choices=[('II and III', 1), ('IV', 2), ('V', 3)], verbose_name='Seismic Zone'),
        ),
        migrations.AlterField(
            model_name='rc_building',
            name='yr_extn',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Year of Extension (If Any)'),
        ),
    ]
