# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 20:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0018_auto_20170622_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='rc_building',
            name='yr_aval',
            field=models.BooleanField(default=False, verbose_name='Not Available?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rc_building',
            name='yr_constr',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2017)], verbose_name='Year of Construction'),
        ),
    ]
