# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 20:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0019_auto_20170623_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rc_building',
            name='yr_constr',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2017)], verbose_name='Year of Construction'),
        ),
    ]
