# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 20:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0020_auto_20170623_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='rc_building',
            name='oc_navl',
            field=models.BooleanField(default=False, verbose_name='Occupancy Data Not Available?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rc_building',
            name='no_floor',
            field=models.DecimalField(decimal_places=0, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='No. of Floors'),
        ),
        migrations.AlterField(
            model_name='rc_building',
            name='oc_night',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Night'),
        ),
    ]
