# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0020_auto_20170617_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='rc_building',
            name='frm_act',
            field=models.NullBooleanField(verbose_name='Frame Action Present? '),
        ),
    ]
