# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 21:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0021_auto_20170623_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rc_building',
            name='oc_day',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='rc_building',
            name='oc_night',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Night'),
        ),
    ]
