# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0021_rc_building_frm_act'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rc_building',
            name='frm_act',
            field=models.NullBooleanField(verbose_name='Frame Action Present'),
        ),
        migrations.AlterField(
            model_name='rc_building',
            name='oc_day',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='rc_building',
            name='oc_night',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Night'),
        ),
    ]
