# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0023_auto_20170623_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hy_building',
            name='oc_navl',
            field=models.BooleanField(verbose_name='Not Available?'),
        ),
        migrations.AlterField(
            model_name='ms_building',
            name='oc_navl',
            field=models.BooleanField(verbose_name='Not Available?'),
        ),
        migrations.AlterField(
            model_name='rc_building',
            name='oc_navl',
            field=models.BooleanField(verbose_name='Not Available?'),
        ),
    ]
